function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function falsy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "false" || value === "0"
}

// Support both INNOCODE_ and OPENCODE_ prefixes, with INNOCODE_ taking precedence
function getEnv(innocodeKey: string, opencodeKey: string): string | undefined {
  return process.env[innocodeKey] ?? process.env[opencodeKey]
}

function getTruthy(innocodeKey: string, opencodeKey: string): boolean {
  return truthy(innocodeKey) || truthy(opencodeKey)
}

function getFalsy(innocodeKey: string, opencodeKey: string): boolean {
  return falsy(innocodeKey) || falsy(opencodeKey)
}

export namespace Flag {
  export const OPENCODE_AUTO_SHARE = getTruthy("INNOCODE_AUTO_SHARE", "OPENCODE_AUTO_SHARE")
  export const OPENCODE_GIT_BASH_PATH = getEnv("INNOCODE_GIT_BASH_PATH", "OPENCODE_GIT_BASH_PATH")
  export const OPENCODE_CONFIG = getEnv("INNOCODE_CONFIG", "OPENCODE_CONFIG")
  export declare const OPENCODE_TUI_CONFIG: string | undefined
  export declare const OPENCODE_CONFIG_DIR: string | undefined
  export const OPENCODE_CONFIG_CONTENT = getEnv("INNOCODE_CONFIG_CONTENT", "OPENCODE_CONFIG_CONTENT")
  export const OPENCODE_DISABLE_AUTOUPDATE = getTruthy("INNOCODE_DISABLE_AUTOUPDATE", "OPENCODE_DISABLE_AUTOUPDATE")
  export const OPENCODE_DISABLE_PRUNE = getTruthy("INNOCODE_DISABLE_PRUNE", "OPENCODE_DISABLE_PRUNE")
  export const OPENCODE_DISABLE_TERMINAL_TITLE = getTruthy("INNOCODE_DISABLE_TERMINAL_TITLE", "OPENCODE_DISABLE_TERMINAL_TITLE")
  export const OPENCODE_PERMISSION = getEnv("INNOCODE_PERMISSION", "OPENCODE_PERMISSION")
  export const OPENCODE_DISABLE_DEFAULT_PLUGINS = getTruthy("INNOCODE_DISABLE_DEFAULT_PLUGINS", "OPENCODE_DISABLE_DEFAULT_PLUGINS")
  export const OPENCODE_DISABLE_LSP_DOWNLOAD = getTruthy("INNOCODE_DISABLE_LSP_DOWNLOAD", "OPENCODE_DISABLE_LSP_DOWNLOAD")
  export const OPENCODE_ENABLE_EXPERIMENTAL_MODELS = getTruthy("INNOCODE_ENABLE_EXPERIMENTAL_MODELS", "OPENCODE_ENABLE_EXPERIMENTAL_MODELS")
  export const OPENCODE_DISABLE_AUTOCOMPACT = getTruthy("INNOCODE_DISABLE_AUTOCOMPACT", "OPENCODE_DISABLE_AUTOCOMPACT")
  export const OPENCODE_DISABLE_MODELS_FETCH = getTruthy("INNOCODE_DISABLE_MODELS_FETCH", "OPENCODE_DISABLE_MODELS_FETCH")
  export const OPENCODE_DISABLE_CLAUDE_CODE = getTruthy("INNOCODE_DISABLE_CLAUDE_CODE", "OPENCODE_DISABLE_CLAUDE_CODE")
  export const OPENCODE_DISABLE_CLAUDE_CODE_PROMPT =
    OPENCODE_DISABLE_CLAUDE_CODE || getTruthy("INNOCODE_DISABLE_CLAUDE_CODE_PROMPT", "OPENCODE_DISABLE_CLAUDE_CODE_PROMPT")
  export const OPENCODE_DISABLE_CLAUDE_CODE_SKILLS =
    OPENCODE_DISABLE_CLAUDE_CODE || getTruthy("INNOCODE_DISABLE_CLAUDE_CODE_SKILLS", "OPENCODE_DISABLE_CLAUDE_CODE_SKILLS")
  export const OPENCODE_DISABLE_EXTERNAL_SKILLS =
    OPENCODE_DISABLE_CLAUDE_CODE_SKILLS || getTruthy("INNOCODE_DISABLE_EXTERNAL_SKILLS", "OPENCODE_DISABLE_EXTERNAL_SKILLS")
  export declare const OPENCODE_DISABLE_PROJECT_CONFIG: boolean
  export const OPENCODE_FAKE_VCS = getEnv("INNOCODE_FAKE_VCS", "OPENCODE_FAKE_VCS")
  export declare const OPENCODE_CLIENT: string
  export const OPENCODE_SERVER_PASSWORD = getEnv("INNOCODE_SERVER_PASSWORD", "OPENCODE_SERVER_PASSWORD")
  export const OPENCODE_SERVER_USERNAME = getEnv("INNOCODE_SERVER_USERNAME", "OPENCODE_SERVER_USERNAME")
  export const OPENCODE_ENABLE_QUESTION_TOOL = getTruthy("INNOCODE_ENABLE_QUESTION_TOOL", "OPENCODE_ENABLE_QUESTION_TOOL")

  // Experimental
  export const OPENCODE_EXPERIMENTAL = getTruthy("INNOCODE_EXPERIMENTAL", "OPENCODE_EXPERIMENTAL")
  export const OPENCODE_EXPERIMENTAL_FILEWATCHER = getTruthy("INNOCODE_EXPERIMENTAL_FILEWATCHER", "OPENCODE_EXPERIMENTAL_FILEWATCHER")
  export const OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER = getTruthy("INNOCODE_EXPERIMENTAL_DISABLE_FILEWATCHER", "OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER")
  export const OPENCODE_EXPERIMENTAL_ICON_DISCOVERY =
    OPENCODE_EXPERIMENTAL || getTruthy("INNOCODE_EXPERIMENTAL_ICON_DISCOVERY", "OPENCODE_EXPERIMENTAL_ICON_DISCOVERY")

  const copy = getEnv("INNOCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT", "OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
  export const OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT =
    copy === undefined ? process.platform === "win32" : getTruthy("INNOCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT", "OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
  export const OPENCODE_ENABLE_EXA =
    getTruthy("INNOCODE_ENABLE_EXA", "OPENCODE_ENABLE_EXA") || OPENCODE_EXPERIMENTAL || getTruthy("INNOCODE_EXPERIMENTAL_EXA", "OPENCODE_EXPERIMENTAL_EXA")
  export const OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = number("INNOCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS", "OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS")
  export const OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX = number("INNOCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX", "OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
  export const OPENCODE_EXPERIMENTAL_OXFMT = OPENCODE_EXPERIMENTAL || getTruthy("INNOCODE_EXPERIMENTAL_OXFMT", "OPENCODE_EXPERIMENTAL_OXFMT")
  export const OPENCODE_EXPERIMENTAL_LSP_TY = getTruthy("INNOCODE_EXPERIMENTAL_LSP_TY", "OPENCODE_EXPERIMENTAL_LSP_TY")
  export const OPENCODE_EXPERIMENTAL_LSP_TOOL = OPENCODE_EXPERIMENTAL || getTruthy("INNOCODE_EXPERIMENTAL_LSP_TOOL", "OPENCODE_EXPERIMENTAL_LSP_TOOL")
  export const OPENCODE_DISABLE_FILETIME_CHECK = getTruthy("INNOCODE_DISABLE_FILETIME_CHECK", "OPENCODE_DISABLE_FILETIME_CHECK")
  export const OPENCODE_EXPERIMENTAL_PLAN_MODE = OPENCODE_EXPERIMENTAL || getTruthy("INNOCODE_EXPERIMENTAL_PLAN_MODE", "OPENCODE_EXPERIMENTAL_PLAN_MODE")
  export const OPENCODE_EXPERIMENTAL_WORKSPACES = OPENCODE_EXPERIMENTAL || getTruthy("INNOCODE_EXPERIMENTAL_WORKSPACES", "OPENCODE_EXPERIMENTAL_WORKSPACES")
  export const OPENCODE_EXPERIMENTAL_MARKDOWN = !getFalsy("INNOCODE_EXPERIMENTAL_MARKDOWN", "OPENCODE_EXPERIMENTAL_MARKDOWN")
  export const OPENCODE_MODELS_URL = getEnv("INNOCODE_MODELS_URL", "OPENCODE_MODELS_URL")
  export const OPENCODE_MODELS_PATH = getEnv("INNOCODE_MODELS_PATH", "OPENCODE_MODELS_PATH")
  export const OPENCODE_DISABLE_CHANNEL_DB = getTruthy("INNOCODE_DISABLE_CHANNEL_DB", "OPENCODE_DISABLE_CHANNEL_DB")
  export const OPENCODE_SKIP_MIGRATIONS = getTruthy("INNOCODE_SKIP_MIGRATIONS", "OPENCODE_SKIP_MIGRATIONS")
  export const OPENCODE_STRICT_CONFIG_DEPS = getTruthy("INNOCODE_STRICT_CONFIG_DEPS", "OPENCODE_STRICT_CONFIG_DEPS")

  function number(innocodeKey: string, opencodeKey: string) {
    const value = getEnv(innocodeKey, opencodeKey)
    if (!value) return undefined
    const parsed = Number(value)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }
}

// Dynamic getter for OPENCODE_DISABLE_PROJECT_CONFIG
Object.defineProperty(Flag, "OPENCODE_DISABLE_PROJECT_CONFIG", {
  get() {
    return truthy("INNOCODE_DISABLE_PROJECT_CONFIG") || truthy("OPENCODE_DISABLE_PROJECT_CONFIG")
  },
  enumerable: true,
  configurable: false,
})

// Dynamic getter for OPENCODE_TUI_CONFIG
Object.defineProperty(Flag, "OPENCODE_TUI_CONFIG", {
  get() {
    return process.env["INNOCODE_TUI_CONFIG"] ?? process.env["OPENCODE_TUI_CONFIG"]
  },
  enumerable: true,
  configurable: false,
})

// Dynamic getter for OPENCODE_CONFIG_DIR
Object.defineProperty(Flag, "OPENCODE_CONFIG_DIR", {
  get() {
    return process.env["INNOCODE_CONFIG_DIR"] ?? process.env["OPENCODE_CONFIG_DIR"]
  },
  enumerable: true,
  configurable: false,
})

// Dynamic getter for OPENCODE_CLIENT
Object.defineProperty(Flag, "OPENCODE_CLIENT", {
  get() {
    return process.env["INNOCODE_CLIENT"] ?? process.env["OPENCODE_CLIENT"] ?? "cli"
  },
  enumerable: true,
  configurable: false,
})
