function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

// Support both INNOCODE_ and OPENCODE_ prefixes, with INNOCODE_ taking precedence
function getEnv(innocodeKey: string, opencodeKey: string): string | undefined {
  return process.env[innocodeKey] ?? process.env[opencodeKey]
}

function getTruthy(innocodeKey: string, opencodeKey: string): boolean {
  return truthy(innocodeKey) || truthy(opencodeKey)
}

export namespace Flag {
  export const INNOCODE_AUTO_SHARE = getTruthy("INNOCODE_AUTO_SHARE", "OPENCODE_AUTO_SHARE")
  export const INNOCODE_GIT_BASH_PATH = getEnv("INNOCODE_GIT_BASH_PATH", "OPENCODE_GIT_BASH_PATH")
  export const INNOCODE_CONFIG = getEnv("INNOCODE_CONFIG", "OPENCODE_CONFIG")
  export declare const INNOCODE_CONFIG_DIR: string | undefined
  export declare const OPENCODE_CONFIG_DIR: string | undefined
  export const INNOCODE_CONFIG_CONTENT = getEnv("INNOCODE_CONFIG_CONTENT", "OPENCODE_CONFIG_CONTENT")
  export const INNOCODE_DISABLE_AUTOUPDATE = getTruthy("INNOCODE_DISABLE_AUTOUPDATE", "OPENCODE_DISABLE_AUTOUPDATE")
  export const INNOCODE_DISABLE_PRUNE = getTruthy("INNOCODE_DISABLE_PRUNE", "OPENCODE_DISABLE_PRUNE")
  export const INNOCODE_DISABLE_TERMINAL_TITLE = getTruthy("INNOCODE_DISABLE_TERMINAL_TITLE", "OPENCODE_DISABLE_TERMINAL_TITLE")
  export const INNOCODE_PERMISSION = getEnv("INNOCODE_PERMISSION", "OPENCODE_PERMISSION")
  export const INNOCODE_DISABLE_DEFAULT_PLUGINS = getTruthy("INNOCODE_DISABLE_DEFAULT_PLUGINS", "OPENCODE_DISABLE_DEFAULT_PLUGINS")
  export const INNOCODE_DISABLE_LSP_DOWNLOAD = getTruthy("INNOCODE_DISABLE_LSP_DOWNLOAD", "OPENCODE_DISABLE_LSP_DOWNLOAD")
  export const INNOCODE_ENABLE_EXPERIMENTAL_MODELS = getTruthy("INNOCODE_ENABLE_EXPERIMENTAL_MODELS", "OPENCODE_ENABLE_EXPERIMENTAL_MODELS")
  export const INNOCODE_DISABLE_AUTOCOMPACT = getTruthy("INNOCODE_DISABLE_AUTOCOMPACT", "OPENCODE_DISABLE_AUTOCOMPACT")
  export const INNOCODE_DISABLE_MODELS_FETCH = getTruthy("INNOCODE_DISABLE_MODELS_FETCH", "OPENCODE_DISABLE_MODELS_FETCH")
  export const INNOCODE_DISABLE_CLAUDE_CODE = getTruthy("INNOCODE_DISABLE_CLAUDE_CODE", "OPENCODE_DISABLE_CLAUDE_CODE")
  export const INNOCODE_DISABLE_CLAUDE_CODE_PROMPT =
    INNOCODE_DISABLE_CLAUDE_CODE || getTruthy("INNOCODE_DISABLE_CLAUDE_CODE_PROMPT", "OPENCODE_DISABLE_CLAUDE_CODE_PROMPT")
  export const INNOCODE_DISABLE_CLAUDE_CODE_SKILLS =
    INNOCODE_DISABLE_CLAUDE_CODE || getTruthy("INNOCODE_DISABLE_CLAUDE_CODE_SKILLS", "OPENCODE_DISABLE_CLAUDE_CODE_SKILLS")
  export declare const INNOCODE_DISABLE_PROJECT_CONFIG: boolean
  export declare const OPENCODE_DISABLE_PROJECT_CONFIG: boolean
  export const INNOCODE_FAKE_VCS = getEnv("INNOCODE_FAKE_VCS", "OPENCODE_FAKE_VCS")
  export const INNOCODE_CLIENT = getEnv("INNOCODE_CLIENT", "OPENCODE_CLIENT") ?? "cli"
  export const INNOCODE_SERVER_PASSWORD = getEnv("INNOCODE_SERVER_PASSWORD", "OPENCODE_SERVER_PASSWORD")
  export const INNOCODE_SERVER_USERNAME = getEnv("INNOCODE_SERVER_USERNAME", "OPENCODE_SERVER_USERNAME")

  // Experimental
  export const INNOCODE_EXPERIMENTAL = getTruthy("INNOCODE_EXPERIMENTAL", "OPENCODE_EXPERIMENTAL")
  export const INNOCODE_EXPERIMENTAL_FILEWATCHER = getTruthy("INNOCODE_EXPERIMENTAL_FILEWATCHER", "OPENCODE_EXPERIMENTAL_FILEWATCHER")
  export const INNOCODE_EXPERIMENTAL_DISABLE_FILEWATCHER = getTruthy("INNOCODE_EXPERIMENTAL_DISABLE_FILEWATCHER", "OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER")
  export const INNOCODE_EXPERIMENTAL_ICON_DISCOVERY =
    INNOCODE_EXPERIMENTAL || getTruthy("INNOCODE_EXPERIMENTAL_ICON_DISCOVERY", "OPENCODE_EXPERIMENTAL_ICON_DISCOVERY")
  export const INNOCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = getTruthy("INNOCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT", "OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT")
  export const INNOCODE_ENABLE_EXA =
    getTruthy("INNOCODE_ENABLE_EXA", "OPENCODE_ENABLE_EXA") || INNOCODE_EXPERIMENTAL || getTruthy("INNOCODE_EXPERIMENTAL_EXA", "OPENCODE_EXPERIMENTAL_EXA")
  export const INNOCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH = number("INNOCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH", "OPENCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH")
  export const INNOCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = number("INNOCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS", "OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS")
  export const INNOCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX = number("INNOCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX", "OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX")
  export const INNOCODE_EXPERIMENTAL_OXFMT = INNOCODE_EXPERIMENTAL || getTruthy("INNOCODE_EXPERIMENTAL_OXFMT", "OPENCODE_EXPERIMENTAL_OXFMT")
  export const INNOCODE_EXPERIMENTAL_LSP_TY = getTruthy("INNOCODE_EXPERIMENTAL_LSP_TY", "OPENCODE_EXPERIMENTAL_LSP_TY")
  export const INNOCODE_EXPERIMENTAL_LSP_TOOL = INNOCODE_EXPERIMENTAL || getTruthy("INNOCODE_EXPERIMENTAL_LSP_TOOL", "OPENCODE_EXPERIMENTAL_LSP_TOOL")
  export const INNOCODE_DISABLE_FILETIME_CHECK = getTruthy("INNOCODE_DISABLE_FILETIME_CHECK", "OPENCODE_DISABLE_FILETIME_CHECK")
  export const INNOCODE_EXPERIMENTAL_PLAN_MODE = INNOCODE_EXPERIMENTAL || getTruthy("INNOCODE_EXPERIMENTAL_PLAN_MODE", "OPENCODE_EXPERIMENTAL_PLAN_MODE")
  export const INNOCODE_EXPERIMENTAL_MARKDOWN = getTruthy("INNOCODE_EXPERIMENTAL_MARKDOWN", "OPENCODE_EXPERIMENTAL_MARKDOWN")
  export const INNOCODE_MODELS_URL = getEnv("INNOCODE_MODELS_URL", "OPENCODE_MODELS_URL")

  // Legacy aliases (for backwards compatibility with OPENCODE_ prefix)
  export const OPENCODE_AUTO_SHARE = INNOCODE_AUTO_SHARE
  export const OPENCODE_GIT_BASH_PATH = INNOCODE_GIT_BASH_PATH
  export const OPENCODE_CONFIG = INNOCODE_CONFIG
  export const OPENCODE_CONFIG_CONTENT = INNOCODE_CONFIG_CONTENT
  export const OPENCODE_DISABLE_AUTOUPDATE = INNOCODE_DISABLE_AUTOUPDATE
  export const OPENCODE_DISABLE_PRUNE = INNOCODE_DISABLE_PRUNE
  export const OPENCODE_DISABLE_TERMINAL_TITLE = INNOCODE_DISABLE_TERMINAL_TITLE
  export const OPENCODE_PERMISSION = INNOCODE_PERMISSION
  export const OPENCODE_DISABLE_DEFAULT_PLUGINS = INNOCODE_DISABLE_DEFAULT_PLUGINS
  export const OPENCODE_DISABLE_LSP_DOWNLOAD = INNOCODE_DISABLE_LSP_DOWNLOAD
  export const OPENCODE_ENABLE_EXPERIMENTAL_MODELS = INNOCODE_ENABLE_EXPERIMENTAL_MODELS
  export const OPENCODE_DISABLE_AUTOCOMPACT = INNOCODE_DISABLE_AUTOCOMPACT
  export const OPENCODE_DISABLE_MODELS_FETCH = INNOCODE_DISABLE_MODELS_FETCH
  export const OPENCODE_DISABLE_CLAUDE_CODE = INNOCODE_DISABLE_CLAUDE_CODE
  export const OPENCODE_DISABLE_CLAUDE_CODE_PROMPT = INNOCODE_DISABLE_CLAUDE_CODE_PROMPT
  export const OPENCODE_DISABLE_CLAUDE_CODE_SKILLS = INNOCODE_DISABLE_CLAUDE_CODE_SKILLS
  export const OPENCODE_FAKE_VCS = INNOCODE_FAKE_VCS
  export const OPENCODE_CLIENT = INNOCODE_CLIENT
  export const OPENCODE_SERVER_PASSWORD = INNOCODE_SERVER_PASSWORD
  export const OPENCODE_SERVER_USERNAME = INNOCODE_SERVER_USERNAME
  export const OPENCODE_EXPERIMENTAL = INNOCODE_EXPERIMENTAL
  export const OPENCODE_EXPERIMENTAL_FILEWATCHER = INNOCODE_EXPERIMENTAL_FILEWATCHER
  export const OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER = INNOCODE_EXPERIMENTAL_DISABLE_FILEWATCHER
  export const OPENCODE_EXPERIMENTAL_ICON_DISCOVERY = INNOCODE_EXPERIMENTAL_ICON_DISCOVERY
  export const OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT = INNOCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT
  export const OPENCODE_ENABLE_EXA = INNOCODE_ENABLE_EXA
  export const OPENCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH = INNOCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH
  export const OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS = INNOCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS
  export const OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX = INNOCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX
  export const OPENCODE_EXPERIMENTAL_OXFMT = INNOCODE_EXPERIMENTAL_OXFMT
  export const OPENCODE_EXPERIMENTAL_LSP_TY = INNOCODE_EXPERIMENTAL_LSP_TY
  export const OPENCODE_EXPERIMENTAL_LSP_TOOL = INNOCODE_EXPERIMENTAL_LSP_TOOL
  export const OPENCODE_DISABLE_FILETIME_CHECK = INNOCODE_DISABLE_FILETIME_CHECK
  export const OPENCODE_EXPERIMENTAL_PLAN_MODE = INNOCODE_EXPERIMENTAL_PLAN_MODE
  export const OPENCODE_EXPERIMENTAL_MARKDOWN = INNOCODE_EXPERIMENTAL_MARKDOWN
  export const OPENCODE_MODELS_URL = INNOCODE_MODELS_URL

  function number(innocodeKey: string, opencodeKey: string) {
    const value = getEnv(innocodeKey, opencodeKey)
    if (!value) return undefined
    const parsed = Number(value)
    return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
  }
}

// Dynamic getter for INNOCODE_DISABLE_PROJECT_CONFIG
Object.defineProperty(Flag, "INNOCODE_DISABLE_PROJECT_CONFIG", {
  get() {
    return truthy("INNOCODE_DISABLE_PROJECT_CONFIG") || truthy("OPENCODE_DISABLE_PROJECT_CONFIG")
  },
  enumerable: true,
  configurable: false,
})

// Legacy alias
Object.defineProperty(Flag, "OPENCODE_DISABLE_PROJECT_CONFIG", {
  get() {
    return (Flag as any).INNOCODE_DISABLE_PROJECT_CONFIG
  },
  enumerable: true,
  configurable: false,
})

// Dynamic getter for INNOCODE_CONFIG_DIR
Object.defineProperty(Flag, "INNOCODE_CONFIG_DIR", {
  get() {
    return process.env["INNOCODE_CONFIG_DIR"] ?? process.env["OPENCODE_CONFIG_DIR"]
  },
  enumerable: true,
  configurable: false,
})

// Legacy alias
Object.defineProperty(Flag, "OPENCODE_CONFIG_DIR", {
  get() {
    return (Flag as any).INNOCODE_CONFIG_DIR
  },
  enumerable: true,
  configurable: false,
})
